node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("cbinh951/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
  stage('Run App') {
     sh "docker pull cbinh951/docker-nodejs-demo"
     sh "docker run -d --rm -p 3000:3000 cbinh951/docker-nodejs-demo:${commit_id}"
     echo "Application started on port: 3000 (http)"
   }
}
